package com.gal.afiliaciones.infrastructure.dto;

public record UpdateInfoBasicaRequest(
        String primerNombre,
        String segundoNombre,
        String primerApellido,
        String segundoApellido,
        java.time.LocalDate fechaNacimiento,
        String nacionalidad,
        String sexo,
        String afp,
        String eps,
        String email,
        String confirmarEmail,
        String telefono1,
        String telefono2,
        Integer idDepartamento,
        Integer idCiudad,
        String idCallePrincipal,
        String numeroCallePrincipal,
        String letra1CallePrincipal,
        String letra2CallePrincipal,
        String puntoCardinalCallePrincipal,
        Boolean bis,
        String numero1Secundaria,
        String numero2Secundaria,
        String letraSecundaria,
        String puntoCardinal2,
        String ph1, String numPh1,
        String ph2, String numPh2,
        String ph3, String numPh3,
        String ph4, String numPh4,
        String direccionTexto,
        Integer idCargo,
        java.time.LocalDate fechaNovedad,
        String observaciones,
        Integer idCausalNovedad
) {}
