package com.gal.afiliaciones.infrastructure.dto.affiliate.affiliationemployeractivitiesmercantile;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class FullDataMercantileDTO {

    private Long id;
    private String typeDocumentIdentification;
    private String numberIdentification;
    private Integer digitVerificationDV;
    private String businessName;
    private String typePerson;
    private Long numberWorkers;
    private String zoneLocationEmployer;
    private Long department;
    private Long cityMunicipality;
    private String phoneOne;
    private String phoneTwo;
    private String email;
    private String numberDocumentPersonResponsible;
    private String typeDocumentPersonResponsible;
    private String address;
    private Long idMainStreet;
    private Long idNumberMainStreet;
    private Long idLetter1MainStreet;
    private Boolean isBis;
    private Long idLetter2MainStreet;
    private Long idCardinalPointMainStreet;
    private Long idNum1SecondStreet;
    private Long idLetterSecondStreet;
    private Long idNum2SecondStreet;
    private Long idCardinalPoint2;
    private Long idHorizontalProperty1;
    private Long idNumHorizontalProperty1;
    private Long idHorizontalProperty2;
    private Long idNumHorizontalProperty2;
    private Long idHorizontalProperty3;
    private Long idNumHorizontalProperty3;
    private Long idHorizontalProperty4;
    private Long idNumHorizontalProperty4;
    private String affiliationStatus;
    private Long idTypeEmployer;
    private Long idSubTypeEmployer;
    private String arl;
    private LocalDateTime dateInterview;
    private String typeAffiliation;
    private String subTypeAffiliation;
    private Long departmentContactCompany;
    private Long cityMunicipalityContactCompany;
    private String addressContactCompany;
    private Long idMainStreetContactCompany;
    private Long idNumberMainStreetContactCompany;
    private Long idLetter1MainStreetContactCompany;
    private Boolean isBisContactCompany;
    private Long idLetter2MainStreetContactCompany;
    private Long idCardinalPointMainStreetContactCompany;
    private Long idNum1SecondStreetContactCompany;
    private Long idLetterSecondStreetContactCompany;
    private Long idNum2SecondStreetContactCompany;
    private Long idCardinalPoint2ContactCompany;
    private Long idHorizontalProperty1ContactCompany;
    private Long idNumHorizontalProperty1ContactCompany;
    private Long idHorizontalProperty2ContactCompany;
    private Long idNumHorizontalProperty2ContactCompany;
    private Long idHorizontalProperty3ContactCompany;
    private Long idNumHorizontalProperty3ContactCompany;
    private Long idHorizontalProperty4ContactCompany;
    private Long idNumHorizontalProperty4ContactCompany;
    private String phoneOneContactCompany;
    private String phoneTwoContactCompany;
    private String emailContactCompany;
    private Long idUserPreRegister;
    private Long afp;
    private Long eps;
    private String filedNumber;
    private String dateRequest;
    private LocalDate dateCreateAffiliate;
    private String stageManagement;
    private String idFolderAlfresco;
    private Boolean affiliationCancelled;
    private Boolean statusDocument;
    private Long activityEconomicPrimary;
    private Long activityEconomicSecondaryOne;
    private Long activityEconomicSecondaryTwo;
    private Long activityEconomicSecondaryThree;
    private Long activityEconomicSecondaryFour;
    private String addressLegalRepresentative;
    private Long idDepartmentLegalRepresentative;
    private Long idCityLegalRepresentative;
    private Long idMainStreetLegalRepresentative;
    private Long idNumberMainStreetLegalRepresentative;
    private Long idLetter1MainStreetLegalRepresentative;
    private Boolean isBisLegalRepresentative;
    private Long idLetter2MainStreetLegalRepresentative;
    private Long idCardinalPointMainStreetLegalRepresentative;
    private Long idNum1SecondStreetLegalRepresentative;
    private Long idLetterSecondStreetLegalRepresentative;
    private Long idNum2SecondStreetLegalRepresentative;
    private Long idCardinalPoint2LegalRepresentative;
    private Long idHorizontalProperty1LegalRepresentative;
    private Long idNumHorizontalProperty1LegalRepresentative;
    private Long idHorizontalProperty2LegalRepresentative;
    private Long idNumHorizontalProperty2LegalRepresentative;
    private Long idHorizontalProperty3LegalRepresentative;
    private Long idNumHorizontalProperty3LegalRepresentative;
    private Long idHorizontalProperty4LegalRepresentative;
    private Long idNumHorizontalProperty4LegalRepresentative;
    private String firstNameLegalRepresentative;
    private String lastNameLegalRepresentative;
    private String surnameLegalRepresentative;
    private String secondSurnameLegalRepresentative;
    private String dateBirthLegalRepresentative;
    private String ageLegalRepresentative;
    private String sexLegalRepresentative;
    private String nacionalityLegalRepresentative;
    private String emailLegalRepresentative;
    private Boolean addressIsEqualsContactCompany;
    private String phoneOneLegalRepresentative;
    private String phoneTwoLegalRepresentative;
    private String legalStatus;
    private Boolean isVip;
    private Map<Long, Boolean> idActivityEconomic =  new HashMap<>();

}
