package com.gal.afiliaciones.config.ex;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.*;

import java.io.Serializable;
import java.util.List;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Builder
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Error implements Serializable {

    private Type type;
    private String message;
    private List<String> detail;

    public enum Type {
        //200
        MESSAGE_GENERATE_AFFILIATION,
        // 400
        USER_INACTIVE,
        PENDING_AFFILIATION,
        EMAIL_ALREADY_EXISTS,
        PHONE1_ALREADY_EXISTS,
        USER_AND_TYPE_ALREADY_EXISTS,
        INVALID_ARGUMENT,
        INVALID_BODY,
        INVALID_HEADER,
        INVALID_PARAMETER,
        METHOD_NOT_ALLOWED,
        UNSUPPORTED_MEDIA_TYPE,
        INVALID_AUTHORIZER,
        CLIENT_ERROR,
        USER_NOT_CONTAIN_DATA_PERSONAL,
        INVALID_CODE_OTP,
        EXPIRED_CODE_OTP,
        ATTEMPTS_EXAGGERATED,
        CODE_SHORTER_LENGTH,
        CODE_DESCRIPTION_NULL,
        MAXIMUM_ACTIVITIES_ALLOWED,
        DATE_AFFILIATION_ERROR,
        ERROR_GENERATED_CARD,
        AFFILIATE_DATE_ERROR,
        LAST_UPDATED_ERROR,
        WORKER_FOUND,
        FAMILY_MEMBER_DATA_ERROR,
        INVALID_DOCUMENT_TYPE,
        INVALID_DOCUMENT_CONDITIONS,
        PASSWORD_EXPIRED,
        // 401
        AUTHENTICATION_FAILED,
        WORKER_RETIREMENT_ERROR,
        POLICY_NOT_FOUND,

        //404
        USER_NOT_FOUND,
        USER_NOT_FOUND_IN_DATA_BASE,
        USER_NOT_FOUND_IN_REGISTRY,
        RESOURCE_NOT_FOUND,
        DESCRIPTION_NOT_FOUND,
        CODE_CIIU_NOT_FOUND,
        ERROR_TYPE_EMPLOYER_DOCUMENT_REQUESTED,
        ERROR_OPTIONS_WORKSPACE_OFFICIAL,
        NOT_FOUND_WORKERS,
        NOT_FOUND_UPDATES,
        NOT_FOUND_DOCUMENTS_FROM_COLLECTION,
        REGISTER_NOT_FOUND,

        // 409
        INVALID_STATUS,
        INVALID_EMAIL,
        ERROR_NOT_FOUND_CARD,
        AFFILIATION_NOT_FOUND,
        AFFILIATION_RETIRED,
        TEMPORAL_PASSWORD_EXPIRED,

        //422
        MAX_ATTEMPTS,
        INVALID_CODE,
        IDENTIFICATION_TYPE_ERROR,
        SAT_VALIDATION_ERROR,

        // 500
        UNKNOWN_ERROR,
        BUS_ERROR,
        NOT_FOUND_IN_REGISTRY,
        COUNTRY_NOT_FOUND_ERROR,
        DEPARTMENT_NOT_FOUND_ERROR,
        INVALID_IMAGE_FILE_ERROR,
        FILE_STORAGE_ERROR,
        ERROR_VALIDATE_CODE,
        ERROR_UPDATE_USER_KEYCLOAK,
        ERROR_CREATING_SEQUENCE,
        ERROR_SEARCH_PREEMPLOYMENT_EXAM_SITES,
        PASSWORD_INCORRECT,
        ERROR_CREATE_USER_KEYCLOAK,
        ERROR_FIND_DOCUMENT_ALFRESCO,
        ERROR_AFFILIATION,
        ERROR_GET_RESOURCE_KEYCLOAK,
        ERROR_CREATE_RESOURCE_KEYCLOAK,
        ERROR_ASSIGNMENT_RESOURCE_KEYCLOAK,
        ERROR_CONFLICT_KEYCLOAK,
        ERROR_AFFILIATION_ALREADY_EXISTS,
        IBC_LESS_THAN_SMLMV_OR_GREAT_THAN_25_SMLMV,
        ERROR_GENERATING_INDEPENDENT_FORM,
        ACTIVE_SESSION,
        LIMIT_ATTEMPTS_EXCEEDED,
        INDEPENDENT_RELATIONSHIP, NOVELTY_ERROR,
        SAT_UPSTREAM_UNAVAILABLE
    }
}
